# Generated by Django 5.1.1 on 2024-12-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone_api_app', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='wathlist',
            new_name='watchlist',
        ),
    ]
